export interface Proveedor {
    pro_id: number,
    pro_empresa_id: number, 
    pro_tipo_documento_identidad: string,
    pro_documento_identidad: string, 
    pro_nombre_natural: string, 
    pro_razon_social: string,
    pro_observacion: string, 
    pro_telefono: string, 
    pro_celular: string, 
    pro_email: string, 
    pro_pagina_web: string, 
    pro_direccion: string, 
    pro_cedula_representante: string, 
    pro_nombre_presentante: string, 
    pro_telefonos_representante: string, 
    pro_direccion_representante: string, 
    pro_mail_representante: string,
    pro_message_error?: string,
    pro_error_server?: boolean
}